server.port=${PORT:8085}

clients.ps-empresa.url=${PS_EMPRESA_URL}
clients.ps-contrato.url=${PS_CONTRATO_URL}
clients.ps-user.url=${PS_USER_URL}
clients.ps-login.url=${PS_LOGIN_URL}
security.internal-key=${INTERNAL_API_KEY}
app.version=${APP_VERSION:${GIT_COMMIT:unknown}}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
management.endpoint.prometheus.access=read_only

logging.level.root=INFO
logging.level.com.mypetadmin.ps_orchestrator=INFO
